BUG: Use a different name for each macOS wheel name
Use a different name for each macOS wheel name: append the Python minor
version to the name.

Fixes:
```
Error: Failed to CreateArtifact: Received non-retryable error:
Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

raised for example in:
https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/actions/runs/9768626552/job/26966536773?pr=164#step:9:21